SLBMVC/SLBMVC/Controllers/DiscogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SLBMVC.Models;
using SLBMVC.Models.DiscogsConnect;

namespace SLBMVC.Controllers
{
    public class DiscogsController : Controller
    {
        DiscogsApp discogsApp = new DiscogsApp();

        public IActionResult QueryDiscogs()
        {
            List<QueryModel> query = new List<QueryModel>();
            query.Add(new QueryModel());
            return View(query);
        }

        [HttpPost]
        public IActionResult QueryDiscogs(List<QueryModel> queryList, string title = "")
        {
            List<AlbumModel> albumList = new List<AlbumModel>();
            if (title != "")
            {
                queryList.Add(new QueryModel());
                queryList[0].Title = title;
            }

            albumList = discogsApp.CreateListAlbumByQuery(queryList[0].Title);
            if (albumList.Count <= 0 || (albumList[0] is null))
            {
                TempData["Info"] = "No content avalible";
                return View(queryList);
            }
            queryList.AddRange(QueryModel.CreateQueryList(albumList));
            return View(queryList);
        }


        public IActionResult ShowQueryEfect(string title, int id)
        {
            AlbumModel album = discogsApp.CreateAlbumByQuery(title, id);
            ViewBag.id = id;
            ViewBag.title = title;
            return View(album);
        }


        public IActionResult Add(string title, int id)
        {
            AlbumModel album = discogsApp.CreateAlbumByQuery(title, id);
            if (album.Save() == -1) TempData["Info"] = "Erorr, Album didn't saved" ;
            else TempData["Succes"]  ="Album saved to base";

            List<QueryModel> query = new List<QueryModel>();
            query.Add(new QueryModel());
            return Redirect("/Home/Index");
        }
    }
}

SLBMVC/SLBMVC/Controllers/MemoryGameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SLBMVC.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SLBMVC.Controllers
{
    public class MemoryGameController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetAlbums()
        {
            AlbumsJson album = new AlbumsJson();
            return Json(album);
        }
    }
}

SLBMVC/SLBMVC/Views/Shared/_Content.cshtml
@using SLBMVC.Models
@model List<AlbumModel>

@if (TempData["Info"] != null)
{
    <div class="alert alert-info" role="alert">
        @TempData["Info"]
    </div>
}

@if (TempData["Succes"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Succes"]
    </div>
}


<div class="row">
    @for (int i = 0; i <= Model.Count - 1; i++)
    {
        <div class="card col-sm-6 col-md-4 text-center">
            @if (!(@Model[i].Images is null))
            {
                <a asp-action="Album/@Model[i].ID" asp-controller="Home">
                    <img class="rounded-circle center" src="@Model[i].Images[0]" alt="Generic placeholder image" width="140" height="140">
                </a>
            }
            <div class="card-body">
                @if (!(@Model[i].Title is null))
                {
                    <h5 class="card-title">@Model[i].Title</h5>
                }

                <p class="card-text">
                    @if (!(Model[i].Artists is null))
                    {
                        <p class="text">Artist : @Model[i].Artists</p>
                    }
                    @if (@Model[i].Styles.Count > 0)
                    {
                        <p class="text">Style: @Model[i].Styles[0]</p>
                    }
                    @if (@Model[i].Genres.Count > 0)
                    {
                        <p class="text">Genre: @Model[i].Genres[0]</p>
                    }
                    </p>
                </div>
            </div>
     }
</div>

SLBMVC/SLBMVC/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Search Listen Buy</title>

    <!-- Bootstrap core CSS -->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/css/navbar-top-fixed.css" rel="stylesheet">
   
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">SLB</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home<span class="sr-only">(current)</span></a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" asp-controller="MemoryGame" asp-action="Index">Game<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Random">Random album</a>
                </li>
            </ul>
            <form asp-action="QueryDiscogs" asp-controller="Discogs" method="post" class="form-inline mt-2 mt-md-0">
                <input name="title" type="text" class="form-control mr-sm-2" placeholder="All eyez on me" aria-label="Search" />
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <main role="main" class="container">
        @RenderBody()
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="~/lib/jQuery/jquery-3.3.1.min.js"></script>
    <script src="~/lib/popper/popper.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/MemorizeGame/memorize.js"></script>


</body>
</html>

SLBMVC/SLBMVC/Views/Shared/_Show.cshtml
<nav class="navbar navbar-light" style="background-color:#e0e0e0;">
    <a class="navbar-brand" href="#">Styles</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>